import React, { useEffect, useState } from "react";
import SearchFilter from "react-filter-search";
import "./PlayerList.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Row, Col, InputGroup, FormControl, ListGroup } from "react-bootstrap";

let players = [
  { id: 0, title: "A Badoni" },
  { id: 1, title: "A Bawne" },
  { id: 2, title: "A Carey" },
  { id: 3, title: "A Choudhary" },
  { id: 4, title: "A Dananjaya" },
  { id: 5, title: "A Deep" },
  { id: 6, title: "A Dinda" },
  { id: 7, title: "A Finch" },
  { id: 8, title: "A Gautam" },
  { id: 9, title: "A Hales" },
  { id: 10, title: "A Hebbar" },
  { id: 11, title: "A Joseph" },
  { id: 12, title: "A Juyal" },
  { id: 13, title: "A Khan" },
  { id: 14, title: "A Manohar" },
  { id: 15, title: "A Markram" },
  { id: 16, title: "A Mathews" },
  { id: 17, title: "A Milne" },
  { id: 18, title: "A Mishra" },
  { id: 19, title: "A Nath" },
  { id: 20, title: "A Nehra" },
  { id: 21, title: "A Nortje" },
  { id: 22, title: "A Patel" },
  { id: 23, title: "A Rahane" },
  { id: 24, title: "A Rajpoot" },
  { id: 25, title: "A Rashid" },
  { id: 26, title: "A Rawat" },
  { id: 27, title: "A Rayudu" },
  { id: 28, title: "A Roy" },
  { id: 29, title: "A Russell" },
  { id: 30, title: "A Samad" },
  { id: 31, title: "A Sharma" },
  { id: 32, title: "A Singh" },
  { id: 33, title: "A Soni" },
  { id: 34, title: "A Taide" },
  { id: 35, title: "A Tare" },
  { id: 36, title: "A Tendulkar" },
  { id: 37, title: "A Tomar" },
  { id: 38, title: "A Turner" },
  { id: 39, title: "A Tye" },
  { id: 40, title: "A Villiers" },
  { id: 41, title: "A Zampa" },
  { id: 42, title: "B Cutting" },
  { id: 43, title: "B Howell" },
  { id: 44, title: "B Indrajith" },
  { id: 45, title: "B Kumar" },
  { id: 46, title: "B Laughlin" },
  { id: 47, title: "B McCullum" },
  { id: 48, title: "B Rajapaksa" },
  { id: 49, title: "B Sharma" },
  { id: 50, title: "B Singh" },
  { id: 51, title: "B Sran" },
  { id: 52, title: "B Stanlake" },
  { id: 53, title: "B Stokes" },
  { id: 54, title: "B Sudharsan" },
  { id: 55, title: "B Thampi" },
  { id: 56, title: "B Varma" },
  { id: 57, title: "C Anderson" },
  { id: 58, title: "C Brathwaite" },
  { id: 59, title: "C Dala" },
  { id: 60, title: "C Gayle" },
  { id: 61, title: "C Grandhomme" },
  { id: 62, title: "C Green" },
  { id: 63, title: "C Ingram" },
  { id: 64, title: "C Jordan" },
  { id: 65, title: "C Karunaratne" },
  { id: 66, title: "C Lynn" },
  { id: 67, title: "C Milind" },
  { id: 68, title: "C Morris" },
  { id: 69, title: "C Munro" },
  { id: 70, title: "C Sakariya" },
  { id: 71, title: "C Varun" },
  { id: 72, title: "C Woakes" },
  { id: 73, title: "D Bravo" },
  { id: 74, title: "D Brevis" },
  { id: 75, title: "D Chahar" },
  { id: 76, title: "D Chameera" },
  { id: 77, title: "D Christian" },
  { id: 78, title: "D Conway" },
  { id: 79, title: "D Drakes" },
  { id: 80, title: "D Hooda" },
  { id: 81, title: "D Jurel" },
  { id: 82, title: "D Karthik" },
  { id: 83, title: "D Kulkarni" },
  { id: 84, title: "D Malan" },
  { id: 85, title: "D Miller" },
  { id: 86, title: "D Mitchell" },
  { id: 87, title: "D Nalkande" },
  { id: 88, title: "D Padikkal" },
  { id: 89, title: "D Pretorius" },
  { id: 90, title: "D Sams" },
  { id: 91, title: "D Shorey" },
  { id: 92, title: "D Short" },
  { id: 93, title: "D Smith" },
  { id: 94, title: "D Steyn" },
  { id: 95, title: "D Warner" },
  { id: 96, title: "D Willey" },
  { id: 97, title: "E Lewis" },
  { id: 98, title: "E Morgan" },
  { id: 99, title: "F Allen" },
  { id: 100, title: "F Farooqi" },
  { id: 101, title: "F Plessis" },
  { id: 102, title: "G Gambhir" },
  { id: 103, title: "G Garton" },
  { id: 104, title: "G Mann" },
  { id: 105, title: "G Maxwell" },
  { id: 106, title: "G Phillips" },
  { id: 107, title: "G Singh" },
  { id: 108, title: "G Vihari" },
  { id: 109, title: "G Viljoen" },
  { id: 110, title: "H Amla" },
  { id: 111, title: "H Brar" },
  { id: 112, title: "H Dussen" },
  { id: 113, title: "H Gurney" },
  { id: 114, title: "H Klaasen" },
  { id: 115, title: "H Nishaanth" },
  { id: 116, title: "H Pandya" },
  { id: 117, title: "H Patel" },
  { id: 118, title: "H Rana" },
  { id: 119, title: "H Shokeen" },
  { id: 120, title: "H Singh" },
  { id: 121, title: "I Abdulla" },
  { id: 122, title: "I Jaggi" },
  { id: 123, title: "I Kishan" },
  { id: 124, title: "I Pathan" },
  { id: 125, title: "I Porel" },
  { id: 126, title: "I Sharma" },
  { id: 127, title: "I Sodhi" },
  { id: 128, title: "I Tahir" },
  { id: 129, title: "I Udana" },
  { id: 130, title: "J Archer" },
  { id: 131, title: "J Bairstow" },
  { id: 132, title: "J Behrendorff" },
  { id: 133, title: "J Bumrah" },
  { id: 134, title: "J Buttler" },
  { id: 135, title: "J Denly" },
  { id: 136, title: "J Duminy" },
  { id: 137, title: "J Faulkner" },
  { id: 138, title: "J Hazlewood" },
  { id: 139, title: "J Holder" },
  { id: 140, title: "J Neesham" },
  { id: 141, title: "J Pattinson" },
  { id: 142, title: "J Philippe" },
  { id: 143, title: "J Richardson" },
  { id: 144, title: "J Roy" },
  { id: 145, title: "J Saxena" },
  { id: 146, title: "J Scantlebury-Searles" },
  { id: 147, title: "J Sharma" },
  { id: 148, title: "J Suchith" },
  { id: 149, title: "J Unadkat" },
  { id: 150, title: "J Yadav" },
  { id: 151, title: "K Ahmed" },
  { id: 152, title: "K Asif" },
  { id: 153, title: "K Bharat" },
  { id: 154, title: "K Cariappa" },
  { id: 155, title: "K Gowtham" },
  { id: 156, title: "K Jadhav" },
  { id: 157, title: "K Jamieson" },
  { id: 158, title: "K Karthik" },
  { id: 159, title: "K Kartikeya" },
  { id: 160, title: "K Khejroliya" },
  { id: 161, title: "K Mayers" },
  { id: 162, title: "K Nagarkoti" },
  { id: 163, title: "K Nair" },
  { id: 164, title: "K Pandya" },
  { id: 165, title: "K Paul" },
  { id: 166, title: "K Pollard" },
  { id: 167, title: "K Rabada" },
  { id: 168, title: "K Rahul" },
  { id: 169, title: "K Richardson" },
  { id: 170, title: "K Sen" },
  { id: 171, title: "K Sharma" },
  { id: 172, title: "K Sharma" },
  { id: 173, title: "K Tyagi" },
  { id: 174, title: "K Williamson" },
  { id: 175, title: "K Yadav" },
  { id: 176, title: "L Ferguson" },
  { id: 177, title: "L Livingstone" },
  { id: 178, title: "L Meriwala" },
  { id: 179, title: "L Ngidi" },
  { id: 180, title: "L Plunkett" },
  { id: 181, title: "L Simmons" },
  { id: 182, title: "L Sisodia" },
  { id: 183, title: "L Yadav" },
  { id: 184, title: "M Agarwal" },
  { id: 185, title: "M Ali" },
  { id: 186, title: "M Ashwin" },
  { id: 187, title: "M Choudhary" },
  { id: 188, title: "M Dhoni" },
  { id: 189, title: "M Gony" },
  { id: 190, title: "M Guptill" },
  { id: 191, title: "M Henriques" },
  { id: 192, title: "M Henry" },
  { id: 193, title: "M Jansen" },
  { id: 194, title: "M Johnson" },
  { id: 195, title: "M Khan" },
  { id: 196, title: "M Krishna" },
  { id: 197, title: "M Kumar" },
  { id: 198, title: "M Lomror" },
  { id: 199, title: "M Markande" },
  { id: 200, title: "M Marsh" },
  { id: 201, title: "M McClenaghan" },
  { id: 202, title: "M Nabi" },
  { id: 203, title: "M Pandey" },
  { id: 204, title: "M Patel" },
  { id: 205, title: "M Pathirana" },
  { id: 206, title: "M Rahman" },
  { id: 207, title: "M Samuels" },
  { id: 208, title: "M Santner" },
  { id: 209, title: "M Shami" },
  { id: 210, title: "M Sharma" },
  { id: 211, title: "M Singh" },
  { id: 212, title: "M Siraj" },
  { id: 213, title: "M Stoinis" },
  { id: 214, title: "M Theekshana" },
  { id: 215, title: "M Tiwary" },
  { id: 216, title: "M Vijay" },
  { id: 217, title: "M Vohra" },
  { id: 218, title: "M Wade" },
  { id: 219, title: "M Wood" },
  { id: 220, title: "M Yadav" },
  { id: 221, title: "N Ahmad" },
  { id: 222, title: "N Coulter-Nile" },
  { id: 223, title: "N Ellis" },
  { id: 224, title: "N Jagadeesan" },
  { id: 225, title: "N Naik" },
  { id: 226, title: "N Ojha" },
  { id: 227, title: "N Pooran" },
  { id: 228, title: "N Rana" },
  { id: 229, title: "N Saini" },
  { id: 230, title: "N Singh" },
  { id: 231, title: "O McCoy" },
  { id: 232, title: "O Smith" },
  { id: 233, title: "O Thomas" },
  { id: 234, title: "P Barman" },
  { id: 235, title: "P Chameera" },
  { id: 236, title: "P Chawla" },
  { id: 237, title: "P Chopra" },
  { id: 238, title: "P Cummins" },
  { id: 239, title: "P Dubey" },
  { id: 240, title: "P Garg" },
  { id: 241, title: "P Krishna" },
  { id: 242, title: "P Kumar" },
  { id: 243, title: "P Mankad" },
  { id: 244, title: "P Negi" },
  { id: 245, title: "P Patel" },
  { id: 246, title: "P Rajapaksa" },
  { id: 247, title: "P Sangwan" },
  { id: 248, title: "P Shaw" },
  { id: 249, title: "P Silva" },
  { id: 250, title: "P Singh" },
  { id: 251, title: "P Solanki" },
  { id: 252, title: "Q Kock" },
  { id: 253, title: "R Ashwin" },
  { id: 254, title: "R Bawa" },
  { id: 255, title: "R Bhatia" },
  { id: 256, title: "R Bhui" },
  { id: 257, title: "R Bishnoi" },
  { id: 258, title: "R Buddhi" },
  { id: 259, title: "R Chahar" },
  { id: 260, title: "R Dar" },
  { id: 261, title: "R Dhawan" },
  { id: 262, title: "R Dussen" },
  { id: 263, title: "R Gaikwad" },
  { id: 264, title: "R Hangargekar" },
  { id: 265, title: "R Jadeja" },
  { id: 266, title: "R Khan" },
  { id: 267, title: "R Kishore" },
  { id: 268, title: "R Kumar" },
  { id: 269, title: "R Meredith" },
  { id: 270, title: "R Pant" },
  { id: 271, title: "R Parag" },
  { id: 272, title: "R Patel" },
  { id: 273, title: "R Patidar" },
  { id: 274, title: "R Powell" },
  { id: 275, title: "R Salam" },
  { id: 276, title: "R Samarth" },
  { id: 277, title: "R Sharma" },
  { id: 278, title: "R Shepherd" },
  { id: 279, title: "R Singh" },
  { id: 280, title: "R Tewatia" },
  { id: 281, title: "R Tripathi" },
  { id: 282, title: "R Uthappa" },
  { id: 283, title: "R Yadav" },
  { id: 284, title: "S Abbott" },
  { id: 285, title: "S Agarwal" },
  { id: 286, title: "S Ahmed" },
  { id: 287, title: "S Aravind" },
  { id: 288, title: "S Baby" },
  { id: 289, title: "S Badree" },
  { id: 290, title: "S Bharat" },
  { id: 291, title: "S Billings" },
  { id: 292, title: "S Binny" },
  { id: 293, title: "S Cottrell" },
  { id: 294, title: "S Curran" },
  { id: 295, title: "S Dhawan" },
  { id: 296, title: "S Dube" },
  { id: 297, title: "S Dubey" },
  { id: 298, title: "S Garhwal" },
  { id: 299, title: "S Gill" },
  { id: 300, title: "S Gopal" },
  { id: 301, title: "S Goswami" },
  { id: 302, title: "S Hasan" },
  { id: 303, title: "S Hetmyer" },
  { id: 304, title: "S Iyer" },
  { id: 305, title: "S Jackson" },
  { id: 306, title: "S Jakati" },
  { id: 307, title: "S Kaul" },
  { id: 308, title: "S Kaushik" },
  { id: 309, title: "S Khan" },
  { id: 310, title: "S Kuggeleijn" },
  { id: 311, title: "S Lad" },
  { id: 312, title: "S Lamichhane" },
  { id: 313, title: "S Malinga" },
  { id: 314, title: "S Marsh" },
  { id: 315, title: "S Mavi" },
  { id: 316, title: "S Midhun" },
  { id: 317, title: "S Nadeem" },
  { id: 318, title: "S Narine" },
  { id: 319, title: "S Prabhudessai" },
  { id: 320, title: "S Raina" },
  { id: 321, title: "S Rutherford" },
  { id: 322, title: "S Samson" },
  { id: 323, title: "S Senapati" },
  { id: 324, title: "S Sharma" },
  { id: 325, title: "S Singh" },
  { id: 326, title: "S Smith" },
  { id: 327, title: "S Sudharsan" },
  { id: 328, title: "S Thakur" },
  { id: 329, title: "S Tiwary" },
  { id: 330, title: "S Warrier" },
  { id: 331, title: "S Watson" },
  { id: 332, title: "S Yadav" },
  { id: 333, title: "T Banton" },
  { id: 334, title: "T Baroka" },
  { id: 335, title: "T Boult" },
  { id: 336, title: "T Curran" },
  { id: 337, title: "T David" },
  { id: 338, title: "T Deshpande" },
  { id: 339, title: "T Head" },
  { id: 340, title: "T Mills" },
  { id: 341, title: "T Natarajan" },
  { id: 342, title: "T Seifert" },
  { id: 343, title: "T Shamsi" },
  { id: 344, title: "T Southee" },
  { id: 345, title: "T Stubbs" },
  { id: 346, title: "T Varma" },
  { id: 347, title: "U Malik" },
  { id: 348, title: "U Yadav" },
  { id: 349, title: "V Aaron" },
  { id: 350, title: "V Arora" },
  { id: 351, title: "V Chakravarthy" },
  { id: 352, title: "V Iyer" },
  { id: 353, title: "V Kohli" },
  { id: 354, title: "V Ostwal" },
  { id: 355, title: "V Shankar" },
  { id: 356, title: "V Singh" },
  { id: 357, title: "V Vinod" },
  { id: 358, title: "W Chatterjee" },
  { id: 359, title: "W Hasaranga" },
  { id: 360, title: "W Saha" },
  { id: 361, title: "W Sundar" },
  { id: 362, title: "Y Chahal" },
  { id: 363, title: "Y Dayal" },
  { id: 364, title: "Y Dhull" },
  { id: 365, title: "Y Jaiswal" },
  { id: 366, title: "Y Pathan" },
  { id: 367, title: "Y Raj" },
  { id: 368, title: "Y Singh" },
  { id: 369, title: "Z Khan" },
];
const SearchList = () => {
  const [searchInput, setSearchInput] = useState("");

  useEffect(() => {
    console.log(searchInput);
  }, [searchInput]);

  return (
    <div
      className="py-4 px-0"
      style={{
        marginTop: "150px",
        marginLeft: "100px",
      }}
    >
      <Row className="justify-content-start">
        <Col xs={10} md={7} lg={4} className="mb-3" style={{ width: "200px" }}>
          <InputGroup className="mb-3">
            <InputGroup.Text>🔍</InputGroup.Text>
            <FormControl
              placeholder="Search"
              value={searchInput}
              onChange={(e) => setSearchInput(e.target.value)}
            />
          </InputGroup>
        </Col>
        <Col xs={2} lg={2} className="xxx">
          <SearchFilter
            value={searchInput}
            data={players}
            renderResults={(results) => (
              <ListGroup>
                {results.map((item) => (
                  <ListGroup.Item className="mb-1" key={item.id}>{item.title}</ListGroup.Item>
                ))}
              </ListGroup>
            )}
          />
        </Col>
      </Row>
    </div>
  );
};

export default SearchList;
